In [1]:
import torch

Что же такое слой nn.Linear() ?

Давайте проведем несколько эксперименов

Как в случае с бостонским датасетом, мы реализовывали линейную регресиию с помощью nn.Linear() на основе одного признака

То есть имеется:
- 1 числовой признак - in_feature
- 1 числовой выход - out_feature

#### Эксперимент 1

In [240]:
in_feature = 1
out_feature = 1

Тогда линейная регрессия 

$w_0 \times x + b = \hat{y}$ 

задается с помощью одного слоя nn.Linear():



In [241]:
model = torch.nn.Linear(in_feature, out_feature)

Что содержится в данной модели? 

В ней содержатся:

- параметр $w_0$ - `model.weight`

- свободный член/порог $b$ - `model.bias`

In [242]:
model.weight

Parameter containing:
tensor([[-0.4793]], requires_grad=True)

In [244]:
model.bias

Parameter containing:
tensor([0.9904], requires_grad=True)

Посмотрим на размерности всех объектов, участвующих в построении модели: 

- признаковое пространство одного объекта ($x$)
- параметры модели ($w_0$ и $b$)
- выход модели ($\hat{y}$)

In [245]:
x = torch.tensor([5.2])
y_pred = model(x)

In [246]:
for item, name in zip([x, model.weight, model.bias, y_pred], ['x', 'w0', 'b', 'y_pred']):
    print(f'Размерность {name} = {item.shape}')

Размерность x = torch.Size([1])
Размерность w0 = torch.Size([1, 1])
Размерность b = torch.Size([1])
Размерность y_pred = torch.Size([1])


#### Эксперимент 2

Если мы подадим в модель не 1 признак, а 10 признаков

In [247]:
in_feature = 10
out_feature = 1

# новая модель регрессии
model = torch.nn.Linear(in_feature, out_feature)

In [248]:
# определим новый признак как вектор длиной 10 
x = torch.tensor(10*[5.2])
y_pred = model(x)

In [249]:
for item, name in zip([x, model.weight, model.bias, y_pred], ['x', 'w', 'b', 'y_pred']):
    print(f'Размерность {name} = {item.shape}')

Размерность x = torch.Size([10])
Размерность w = torch.Size([1, 10])
Размерность b = torch.Size([1])
Размерность y_pred = torch.Size([1])


#### Эксперимент 3

Теперь пусть кусок сети 6 - 4 - 2, как показано на рисунке. 

Мы рассмотрим скрытый слой, выделенный пунктиром

<img src="MLP.png" width="400">

In [320]:
in_feature = 6
out_feature = 4

# новая модель регрессии
model = torch.nn.Linear(in_feature, out_feature)

In [321]:
# определим новый признак как вектор длиной 6
x = torch.tensor(in_feature*[4.])
y_pred = model(x)

In [322]:
for item, name in zip([x, model.weight, model.bias, y_pred], ['x', 'w', 'b', 'y_pred']):
    print(f'Размерность {name} = {item.shape}')

Размерность x = torch.Size([6])
Размерность w = torch.Size([4, 6])
Размерность b = torch.Size([4])
Размерность y_pred = torch.Size([4])


Согласно документации Pytorch, nn.Linear():

Applies a linear transformation to the incoming data:

<center>$ y = xA^T + b$</center> 


link: https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

In [323]:
all((x @ model.weight.T + model.bias) == y_pred)

True

#### Эксперимент 4

Добавим еще батчевую размерность в наш $x$, но оставим ту же модель

In [333]:
in_feature = 6
out_feature = 4
batch_size = 8

# модель регрессии
model = torch.nn.Linear(in_feature, out_feature)

In [334]:
# определим новый признак как вектор длиной 6 в батче размером 8
x = torch.rand([batch_size, in_feature])
y_pred = model(x)

In [335]:
for item, name in zip([x, model.weight, model.bias, y_pred], ['x', 'w', 'b', 'y_pred']):
    print(f'Размерность {name} = {item.shape}')

Размерность x = torch.Size([8, 6])
Размерность w = torch.Size([4, 6])
Размерность b = torch.Size([4])
Размерность y_pred = torch.Size([8, 4])


In [339]:
((((x @ model.weight.T) + (model.bias.reshape((out_feature, 1)) @ torch.ones([1, batch_size])).T)) == y_pred)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Вопрос 46

In [341]:
in_feature = 20
out_feature = 10
batch_size = 2


# модель регрессии
model = torch.nn.Linear(in_feature, out_feature, bias = False)

In [342]:
# определим новый признак как вектор длиной 6 в батче размером 8
x = torch.rand([batch_size, in_feature])
y_pred = model(x)